model_path: "deepseek/deepseek-r1-distill-llama-70b:free"  # Using Hugging Face API
api_key: "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"  # ✅ Add your API key here

model_config:
    max_new_tokens: 512
    temperature: 0.7
    context_length: 4096
